# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaGIWHLhBwz5fH1OPFkouhuUc6UaKWox
"""

import torch

from torch import nn

from torchvision import datasets

from torchvision import transforms

from datasets import load_dataset

ds = load_dataset("ylecun/mnist")

from torchvision.transforms import ToTensor

train_data = datasets.MNIST(
    root = "data",
    train = True,
    download = True,
    transform = ToTensor(),
    target_transform = None
)

test_data = datasets.MNIST(
    root = "data",
    train = False,
    download = True,
    transform = ToTensor(),
)

device = "cuda" if torch.cuda.is_available() else "cpu"
device

img, label = train_data[0]
img, label

img.shape

import matplotlib.pyplot as plt
plt.imshow(img.squeeze(), cmap = "grey")

class_names = train_data.classes
class_names

from torch.nn.modules.pooling import MaxPool2d
class TinyVGG(nn.Module):
  def __init__(self, input_shape, output_shape, hidden_layers):
    super().__init__()
    self.block_1 = nn.Sequential(
        nn.Conv2d(in_channels = input_shape,
                  out_channels= hidden_layers,
                  kernel_size= 3,
                  padding = 0,
                  stride =1),
        nn.ReLU(),
        nn.Conv2d(in_channels= hidden_layers,
                  out_channels= hidden_layers,
                  kernel_size = 3,
                  padding = 0,
                  stride = 1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size= 2)
    )
    self.block_2 = nn.Sequential(
        nn.Conv2d(in_channels = hidden_layers,
                  out_channels= hidden_layers,
                  kernel_size= 3,
                  padding = 0,
                  stride =1),
        nn.ReLU(),
        nn.Conv2d(in_channels= hidden_layers,
                  out_channels= hidden_layers,
                  kernel_size = 3,
                  padding = 0,
                  stride = 1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size= 2)
    )
    # After block_1 and block_2, the spatial dimensions become 4x4 (for 28x28 input with padding=0 and kernel_size=3 for 2 conv layers and kernel_size=2 for maxpool each block)
    # The in_features for the linear layer should be hidden_layers * 4 * 4
    self.classifier = nn.Sequential(
        nn.Flatten(),
        nn.Linear(in_features = hidden_layers*4*4,
                  out_features= output_shape)
    )
  def forward(self, x):
    x = self.block_1(x)
    x = self.block_2(x)
    x = self.classifier(x)
    return x

model = TinyVGG(input_shape= 1,
                output_shape= 10,
                hidden_layers= 10)

import torch

def train_step(model, dataloader, loss_fn, optimizer, device):
  train_loss, train_acc = 0, 0
  model.train()
  for batch, (X,y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)

    y_pred = model(X)
    loss = loss_fn(y_pred, y)
    train_loss += loss.item()

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    y_pred_class = torch.argmax(torch.softmax(y_pred, dim = 1), dim = 1)
    train_acc += (y_pred_class == y).sum().item() / len(y_pred)
  train_loss /= len(dataloader)
  train_acc /= len(dataloader)
  return train_loss, train_acc

def test_step(model, dataloader, loss_fn, device):
  test_loss, test_acc = 0, 0
  model.eval()
  with torch.inference_mode():
    for batch, (X,y) in enumerate(dataloader):
      X, y = X.to(device), y.to(device)

      y_pred = model(X)
      loss = loss_fn(y_pred, y)
      test_loss += loss.item()

      y_pred_class = torch.argmax(torch.softmax(y_pred, dim = 1), dim = 1)
      test_acc += (y_pred_class == y).sum().item() / len(y_pred)
  test_loss /= len(dataloader)
  test_acc /= len(dataloader)
  return test_loss, test_acc

from torch.utils.data import DataLoader

BATCH_SIZE = 32

train_dataloader = DataLoader(
    train_data,
    BATCH_SIZE,
    shuffle = True
)
test_dataloader = DataLoader(
    test_data,
    BATCH_SIZE,
    shuffle = False
)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)

device = "cuda" if torch.cuda.is_available() else "cpu"
device

from tqdm.auto import tqdm
from typing import Dict, List, Tuple

results = {"train_loss" : [],
             "train_acc" : [],
             "test_loss" : [],
             "test_acc" : []
             }

model.to(device) # Move model to the target device

for epoch in tqdm(range(5)):
    train_loss, train_acc = train_step(model, train_dataloader, loss_fn, optimizer, device)
    test_loss, test_acc = test_step(model, test_dataloader, loss_fn, device)
    print(
          f"Epoch: {epoch+1} | "
          f"train_loss: {train_loss:.4f} | "
          f"train_acc: {train_acc:.4f} | "
          f"test_loss: {test_loss:.4f} | "
          f"test_acc: {test_acc:.4f}"
    )
results["train_loss"].append(train_loss)
results["train_acc"].append(train_acc)
results["test_loss"].append(test_loss)
results["test_acc"].append(test_acc)

results

model.state_dict()

from pathlib import Path

MODEL_PATH = Path("model")
MODEL_PATH.mkdir(parents = True,
                 exist_ok= True)

MODEL_NAME = "MNIST_Computer_Vision.pth"
MODEL_SAVE_PATH = MODEL_PATH/ MODEL_NAME

torch.save(obj = model.state_dict(), f = MODEL_SAVE_PATH)

